### ISSUE TITLE
그리드 높이 조절 질문합니다.

### ISSUE THREAD

**Issue by callakrsos** [ax5ui/ax5ui-grid#1]
안녕하세요.  (( 먼저 이렇게 여기에 글을 올려도 될지.. 잘 모르겠으나  ))

개발된 어플리케이션을 구경하다가 멋져보여서, 샘플을 그대로 따라해보다가...

그리드의 높이를 변경해보려 하였으나 잘 안되서요.  어떻게 설정해야할지 막막해서 

도움을 받을 수 있을까하여, 이렇게 글을 올리게 되었습니다.

http://ax5.io/ax5ui-grid/api/index.html  << api 사이트에 api에 대한 내용이 없고,  웹은 제가 초짜라서요 ^^;  (많이 어렵네요)

긴글 읽어주셔서 감사합니다.

**Comment by thomasJang** [comment]
높이 조절은 아직 API개발전이라 처리 할 수 없습니다.

ax5ui-grid는 지금 막 개발이 진행중입니다. 
test > index.html 에서 최신소스를 확인할 수 있습니다.
제 예상으로는 2주안에 API공개까지 작업이 완료 될 것 같습니다. 조금 더 기다려 주시기 바람니다.

**Comment by callakrsos** [comment]
넵 답변 감사합니다.
