### ISSUE TITLE
안녕하세요, 셀에 이미지를 넣고싶은데 가능한가요?

### ISSUE THREAD

**Issue by jsqim21** [ax5ui/ax5ui-grid#100]
안녕하세요, 

셀에 select 박스나 체크박스는 넣을 수 있지만 혹시 이미지도 넣을 수 있는 방법이 있나요?
예를들어서 셀에 첨부파일이 있을 경우에 첨부파일 아이콘을 띄우고 없는 경우에는 숨기는 형태로요. 

감사합니다.

**Comment by thomasJang** [comment]
https://jsdev.kr/t/topic/2695/4
