### ISSUE TITLE
add row 시 columns 의 key값 문제.

### ISSUE THREAD

**Issue by rcn408** [ax5ui/ax5ui-grid#11]
데이터가
inoutSxn:"001"
totPlMnm:2.2
inputManagementDetails:Array[3]
 0:Object
 actyYymm:"201604"
 mnm:1
 1:Object
 actyYymm:"201605"
 mnm:0.5
 2:Object
 actyYymm:"201606"
 mnm:0.7

이런식으로 inputManagementDetails 에 동적으로 배열이 생성됩니다.

이녀석을 위해서 

          var colMap =
          [  
           {key: 'inoutSxn', label: '<b>구분</b>', width: 40, align: 'center', editor: {type: 'text'}},
           {key: 'totPlMnm', label: '<b>합계</b>', width: 60, align: 'center', formatter: function () {
               return ax5.util.number(.........., {"money": true});
           }}
         ];

          for (var i=0; i<monthdata.length; i++) {
              colMap.push({key: 'inputManagementDetails['+i+'].mnm', label: '<b>' +monthdata[i].actyYymm + '</b>', width: 85, align: 'center',editor:{type: 'money', updateWith:['totPlMnm'], disabled: function() {return false;}}});     
          }

....

Grid 초기화 시에
columns: colMap

요로코롬 하니..일단 데이터가 잘 들어오고..수정도 잘 됩니다.

그런데 신규 행 추가를 하니...
추가 후 동적으로 늘린 행에 값을 입력하면..입력 후 바로 사라져 버리더군요..ㅡㅡ

그래서 key 가 문제인가 싶어...키를 
'inputManagementDetails['+i+'].mnm'  에서 'inputManagementDetails'+i
이런식으로 배열표시( [] )와 ( . ) 을 제거하니.
값을 binding 하지는 못해도 신규 추가시에 입력은 되더군요...

왜 그런지 아직 파악을 못하고 있는 중입니다...ㅡㅡ

기존 HTML과 javascript로 만든 inline editor grid를 수정하면서

테스트를 진행하고 있는데...갈길이 태산이군요..^^;

**Comment by aeei** [comment]
새로 생성한 row 객체에는 "inputManagementDetails" 배열 안에 객체들이 미리 선언되어 있지 않아서, 아래와 같은 방법으로 데이터를 get, set 할 수 없어 말씀하신 문제가 발생한 것 같습니다.

``` js
grid.list["inputManagementDetails"]["0"]["mnm"] = data;
```
> Uncaught TypeError: Cannot set property '0' of undefined

---

저는 inputManagementDetails의 길이만큼 객체를 생성하여 반환하는 getArrayData라는 메서드를 그리드뷰 객체 안에 생성하여 addRow에서 호출하도록 하였습니다.

``` js
fnObj.gridView01 = axboot.viewExtend(axboot.gridView, {
/* ... 생략 ... */
    getArrayData: function (_key) {
        var arr = [],
            obj = {};

        if (_key) {
            for (var i = 0; i < this.target.list[0][_key].length; i++) {
                arr.push({});
            }
            obj[_key] = arr;
        }

        return obj; // { inputManagementDetails: [{},{},...{}] }
    },
    addRow: function () {
        this.target.addRow($.extend({__created__: true}, this.getArrayData("inputManagementDetails")), "last");
    }
});
```

<img width="496" alt="2016-12-27 2 11 21" src="https://cloud.githubusercontent.com/assets/18022843/21484685/304a7ac2-cbda-11e6-8b0c-955fde79d6f8.png" alt="결과캡쳐">

> 결과 캡쳐

**Comment by rcn408** [comment]
감사합니다..^^

**Comment by thomasJang** [comment]
https://guides.github.com/features/mastering-markdown/ 여기를 보면 마크다운 문법설명이 있습니다.
질문하실때에도 가급적 줄을 맞추어 질문해주셔야 답변자가 빠르게 이해 합니다.
