### ISSUE TITLE
로그인 시 모든 테이블의 컬럼 정보조회 막기

### ISSUE THREAD

**Issue by 0rae0926** [ax5ui/ax5ui-grid#119]
### AXBoot를 항상 응원하고 있습니다!

 현재 로그인 페이지를 접근 하거나 로그인 시, 아래 로그처럼 모든 테이블을 조회 하면서 테이블이 

많아 매우 오래 걸립니다.(로그인 시 마다 3~5분가량) 해당 작업을 막으려면 어떻게 하는것이 

좋을까요?

`INFO  com.chequer.axboot.core.db.aop.StatementMethodInterceptor:invoke:149 `
`[query] - 2018-05-25 09:19:02 - `
`    SELECT`
`        A.COLUMN_NAME,`
`        B.COMMENTS `
`    FROM`
`        ALL_TAB_COLUMNS A,`
`        ALL_COL_COMMENTS B `
`    WHERE`
`        A.TABLE_NAME = B.TABLE_NAME `
`        AND  A.COLUMN_NAME = B.COLUMN_NAME `
`        AND A.OWNER = 'SR' `
`        AND A.TABLE_NAME = 'S_RTN_MST_BP'`

**Comment by 0rae0926** [comment]
Chrome에서 개발자모드로 캐쉬지우기 및 강력새로고침 후 했는데도 아직 덜 비워졌었나봅니다.

일정시간 지난뒤 해본결과 답변 내용대로 잘 사용하고있습니다 감사합니다^^

**Comment by aeei** [comment]
해결되셨다니 다행입니다!!
