### ISSUE TITLE
grid excel export bug

### ISSUE THREAD

**Issue by jsw418jj** [ax5ui/ax5ui-grid#12]
grid.js 를 최신버전으로 받아 페이스북에 문의 했던 체크박스 값 표출되는 부분은 해결되었습니다

그런데 추가로 문의 드렸던 숫자값들중 0012 라는 숫자가 있을때 익스포트를 하면 12로 표현이 됩니다
0 이라는 숫자가 없어지는데 버그 인가요??

아니 값을 불러와서 셋팅할때 어떤 이유로 0값을 제거하는 로직이 있는건지 확인 부탁드립니다

**Comment by jsw418jj** [comment]
우선 처리해 주셔서 감사합니다
그리드 파일 패치 받아서 버젼업해서 사용하면 되겠네요 
저도 더 좋은 방법이 있는지 찾아보겠습니다

감사합니다

**Comment by jsw418jj** [comment]
패치 받으면 0 이 없어지는 문제는 우선 처리가 되는거 아니였나요??
지금 그리드js 삭제하고 다시 패치를 받았습니다 
버젼은 1.3.68 입니다
그런데 엑셀 익스포트시 0 이라는 숫자가 없습니다.

패치를 잘못받은건가요??

**Comment by thomasJang** [comment]
http://ax5.io/ax5ui-grid/demo/15-excel-export.html 여기선 되시나요?

**Comment by jsw418jj** [comment]
네 알려주신 url에서는 잘되네요 흠,, 모가 문제 인거지

**Comment by jsw418jj** [comment]
잘처리 되게 신경써주셔서 감사합니다
