### ISSUE TITLE
그리드 행 추가 시 오류

### ISSUE THREAD

**Issue by wjh1001** [ax5ui/ax5ui-grid#13]
아래 처럼 그리드 컬럼 설정 후 행 추가 시 오류가 발생 합니다.

, editor: "text", formatter: function formatter() {
                    return ax5.util.date(this.value, {return:'yyyy/MM/dd'});
}

오류 : Uncaught TypeError: Cannot read property 'getUTCFullYear' of undefined

**Comment by thomasJang** [comment]
ax5core의 date 함수 버그 였습니다.
1.3.79 가 패치 중이니 ax5core를 업데이트 해주세요 감사합니다.
