### ISSUE TITLE
mobile(tablet) scrolling performance issue

### ISSUE THREAD

**Issue by harrymini** [ax5ui/ax5ui-grid#23]
안녕하세요. 
훌륭한 프레임웍을 공유해주셔서 감사합니다.

일반 PC 브라우저에서는 다른 그리드보다 퍼포먼스 측면에서 우수한데요
유독 스크립트 처리가 느린  모바일에서는 느린 것 같습니다. 

하드웨어 가속 css 를 써도 별 차이가 없네요.
-webkit-overflow-scrolling: touch;
transform: translate3d(0, 0, 0);

혹시 개선 방법이 있을까요? 차라리 가상 스크롤을 해제한다던지...

**Comment by thomasJang** [comment]
그리드의 스크롤바는 직접구현된것이라 CSS로는 변경되지 않습니다.
모바일에서 스크립트가 느린것이 아니라. 모바일 터치이벤트가 최근에 변경되어서. 문제가 있는데요. 
가상스크롤 사용여부를 옵션처리 하는 기능은 다음번 릴리즈까지 기다리시면 되겠습니다.

**Comment by thomasJang** [comment]
1.4.5 버전을 이용하세요.

```json
{ 
    virtualScrollY: false,
    virtualScrollX: false
}
```
로 셋팅하면 가상스크롤이 되지 않습니다.
막 만들어서 버그가 있을 수 있으니 버그 발견되면 알려주세요.
