### ISSUE TITLE
tree grid 에서 행 추가

### ISSUE THREAD

**Issue by groovedk** [ax5ui/ax5ui-grid#25]
그리드에서의 행 추가 가능이  트리타입인 경우 마지막에만 추가됩니다. 
지정된 그룹별로 소팅된 기준에서 그리드의 선택된 행 자식 노드의 마지막에 추가한다면 소팅에 문제가 생기지 않고 중간에 추가(자식노드추가)도 가능할거 같습니다.

**Comment by thomasJang** [comment]
pid, id를 위치에 맞게 addRow해보세요
아마 원하는 위치에 추가될 것 같습니다.
