### ISSUE TITLE
Grid에서 select된 Row의 값을 가져오는 방법을 찾고 있습니다.

### ISSUE THREAD

**Issue by kimkang79** [ax5ui/ax5ui-grid#27]
inline-editor방식으로 구현한 Grid에서 
선택(체크박스)되어진 Row들의 특정 컬럼값을 가져오는 방법을 알고 싶습니다.
(API문서에서 제가 찾지 못한 것 일수도....)

ax5ui-grid 데모페이지등을 찾아봤지만 발견하지 못하여 부득이 이곳에 글을 남깁니다.

** 이렇게 좋은 컴포넌드를 만들어주셔서 매우~~~ 감사드립니다!

**Comment by thomasJang** [comment]
getList("selected"); 
입니다. Api에서 selected 만 없네요. 안타깝게도

**Comment by kimkang79** [comment]
이 늦은시간에 빠른답변이라니...
modified나 deleted를 보며 유추했어야 하는데 제가 안타깝네요 ㅠㅠ
