### ISSUE TITLE
Frozen Column&Row 인덱스 설정후 Cell값 변경 문제

### ISSUE THREAD

**Issue by buukiki** [ax5ui/ax5ui-grid#29]
frozenColumnIndex: 3
으로 설정 해놓고 
frozenColumnIndex: 3 이하의 column Cell값은 변경이 되지 않습니다.
별도의 컨트롤 방법이 있는가요?

**Comment by thomasJang** [comment]
Cell값 변경을 어떻게 할 때 안된다는 말씀이신지 모르겠네요.
테스트 샘플에서는 고정된 셀도 inlineEdit됩니다.

<img width="1123" alt="capture 12" src="https://cloud.githubusercontent.com/assets/5884902/25083980/2612e07c-2395-11e7-96c9-c753d7a5b6f5.png">

**Comment by buukiki** [comment]
![cap 2017-04-17 17-45-10-737](https://cloud.githubusercontent.com/assets/19723674/25084103/c216d500-2395-11e7-988c-d54b929b59c4.png)
여기 보시면 칼럼 고정을 시키고 뒤쪽에서 주휴 2를 변경 시키면 총 근로시간을 자동 계산해서 변경
하려 하는데 고정이 되면 변경이 안되서요..
칼럼 고정을 풀면 잘되고요..
별도로 컨트롤 하는 방법이 있는건가 알아봐도 찾기가 힘들어서요

**Comment by thomasJang** [comment]
```
{key: "price", label: "단가", align: "right", editor: {type: "money", updateWith: ['cost']}}
```

값이 변경 되었을 때 updateWith를 설정해서 값을 변경하는데요.
위의 경우 설정이 잘 되었는데도 작동하지 않는지 확인하기 위해 grid setConfig 소스가 있어야 디버깅이 가능하겠습니다.

**Comment by buukiki** [comment]
식이 좀 복잡해서 updateWith를 사용하기에는 무리가 있어서
onDataChanged를 활용해서 grid.setValue 로 변경을 시키려고 하니 잘 안되어서요
ax5ui가 너무 맘에 들어서 꼭 활용하고 싶은데 이부분에서 막혀 지금 고생중이에요..
꼭 updateWith를 사용해야만 되는건가요??

**Comment by thomasJang** [comment]
식은 formatter에 써주시면 되고. updateWith를 설정해주면 되는데요.
어려우시면. 

https://github.com/ax5ui/ax5ui-grid/blob/master/API.md#ax5grid.updateRow
updateRow메소드를 이용해보세요

**Comment by buukiki** [comment]
우선 내일 작업 해보고 다시 결과를 피드백 해보겠습니다.
감사합니다.
