### ISSUE TITLE
특정 컬럼의 색상을 변경하고 싶습니다.

### ISSUE THREAD

**Issue by kimkang79** [ax5ui/ax5ui-grid#36]
Grid에서 특정컬럼의 글자색 혹은 background색상을 변경하는 기능이 있을까요?

"_config.columns[].styleClass"를 사용하면 되지 않을까~싶은데, 
사용법을 찾을 수 없어서 문의 남깁니다.

감사합니다 ^^

**Comment by thomasJang** [comment]
참고하세용

**Comment by kimkang79** [comment]
감사합니다 !

**Comment by kimkang79** [comment]
혹시 위 방법을 찾는 사람이 있을까 싶어 정리 해 둡니다.
1. css 추가
![11](https://cloud.githubusercontent.com/assets/12708061/25309541/1e9c9386-280b-11e7-8548-7641b96807ce.png)
