### ISSUE TITLE
grid tree view 에서 checkbox editor 사용시 이벤트 전달 방법

### ISSUE THREAD

**Issue by groovedk** [ax5ui/ax5ui-grid#37]
grid tree view 에서 checkbox editor 사용시 부모의 클릭 이벤트를 잡아 하위메뉴에 체크를 하고싶습니다. 
어떻게 체크이벤트를 받을 수 있을까요?

![image](https://cloud.githubusercontent.com/assets/5887628/25312272/6c1b9d24-2850-11e7-968b-601142d005a1.png)

**Comment by thomasJang** [comment]
패치된 코드와 예제를 확인하세요

**Comment by groovedk** [comment]
수정된 내용 확인 되었습니다.
그런데 disabled로 컨트롤 한 체크박스에도 값이 적용 되네요.
콜백이나 디스에이블 된 애들은 적용이 되지 않아야 하지 않나 싶습니다.

**Comment by thomasJang** [comment]
변경되면 안되는 조건을 주세요. 처리 해볼게용~~

**Comment by groovedk** [comment]
원글에 첨부한 이미지보시면 체크박스 자리에 Y/N이라고 되어있는 부분은 그리드 에디터 속성에서 디스에이블로 조건을 건 부분인데 
부모를 체크해서 자식들을 체크할때 updateChildRows 호출시 _updatedata 에 함수를 받아서 피해갈 로직을 직접 작성하거나, 디스에이블 조건에 부합시 체크로직을 타지 않으면 되지 않을까 합니다.
