### ISSUE TITLE
Cell 편집 기능 이용시 궁금한게 있습니다.

### ISSUE THREAD

**Issue by ppurefool** [ax5ui/ax5ui-grid#4]
1. Cell Edit Mode 에서(Cell 을 Double Click 하거나 Enter Key 를 누름.)
ESC Key 아닌 Enter Key 를 누르거나, 아래 방향키를 누르거나, 아니면 화면내 다른 곳을 Click 하여
Edit Mode 를 빠져나오면 getList("modified") 에 해당 행이 출력되는거 같습니다.
값이 변경한 행만 출력될 줄 알았는데 그렇지 않네요.

1. Cell 위에서 CapsLock Shift Alt 등의 Key 를 누르면 Edit Mode 로 변경되면서 값을 모두 지우는거 같습니다.
Edit Mode 가 되지도 않으며 값도 변경되지 않을 줄 알았는데 그렇지 않네요.
Notebook Keyboard 라서 못눌러본 Key 들이 더 있네요.(Insert, NumLock 등등)

1. Cell 위에서 ` \ - = [ ] \ ; ' , . / 등의 Key 를 누르면 Edit Mode 로 변경되면서 값을 모두 지우기만 하는거 같습니다. Edit Mode 가 되면서 해당 Key 로 값이 변경될 줄 알았는데 그렇지 않네요.

**Comment by thomasJang** [comment]
1. 값이 변경되지 않으면 modified 상태를 변경하지 않도록 하는게 맞겠네요.
2. 3. 특수키등이 타이핑 될 때 에디팅 문자열 유지 해보겠습니다.

👍
