### ISSUE TITLE
Explorer에서 스크롤 속도개선 문의

### ISSUE THREAD

**Issue by kimkang79** [ax5ui/ax5ui-grid#47]
안녕하세요.

ax5ui-grid(inline-editor)를 사용하여 구현한 화면을 
"크롬"이나 "파이어폭스"에서 사용하면 스크롤이 원활하게 작동됩니다. 
유독 "익스플로러"와 "엣지"에서만 버벅임이 심하구요...

관련문의가 있었나 찾아보니, 해당내용은 없는것 같고...
위와같은 현상이 정상적인건지, 혹은 개선의여지가 있는 것인지 궁금합니다.

**Comment by thomasJang** [comment]
속도 이야기를 하셔서.. 찾아보니. http://jsben.ch/#/yDvKH
이런게 있네요.
그런데 재미있는건 엣지에선 jQuery.html()이 더 빠르네요. 신기하게도

**Comment by thomasJang** [comment]
일단 성능 패치된 버전을 받아서 적용해보세요.
MS브라우저 엔진성능이 좋지 않아서 쉽지는 않겠네요. 제 가상윈도우에서는 성능이 조금 개선 되었는데요.
좀 낳아 졌으면 합니다. 피드백 주세요.

**Comment by kimkang79** [comment]
넵~ 퇴근후에 테스트 해 보고 피드백 드릴게요 ^^ 

감사합니다~!

**Comment by kimkang79** [comment]
익스플로러에서 테스트 해 본 결과, 조금 나아진것 같기도 하고, 아닌것 같기도 하고...
드라마틱한 개선이 이루어지진 않은것 같습니다.

제가 CDN으로 연결해서 사용하고 있는데, 이렇게 하면 최신버전이 적용되고 있는거죠?
![11](https://cloud.githubusercontent.com/assets/12708061/25479910/9149d9ec-2b81-11e7-8c49-eb014a900bef.png)

역시 익스플로러는 크롬이나 파폭보다 못한가봅니다 ㅠ_ㅠ

**Comment by thomasJang** [comment]
아 그런데 CDN이면 캐쉬를 초기화 해야 최신일 것 같아요

콘솔에 `ax5.ui.grid_instance[0].version` 이걸 쳐서 버전을 체크해보세요.

**Comment by kimkang79** [comment]
버전체크를 해보니...1.4.27 입니다.
GitHub에 Release버전은 1.4.30인 걸 보니, CDN말고 다운로드 받아서 사용해봐야 할 것 같습니다.
결과가 나오면 피드백 드리겠습니다~!

**Comment by kimkang79** [comment]
안녕하세요~ 라이브러리 다운받아서 세팅 후, 버전(1.4.30)확인 후 테스트 진행 해 보았습니다.

스크롤이 부드럽다고 할 정도는 아니지만, 이전보다는 약간 개선된 느낌이 있습니다.
이전처럼 툭~툭~끊기는 느낌이 호전된것으로 보여집니다.

**Comment by thomasJang** [comment]
현재로선 그게 최선입니다. 덕분에 크롬에서는 날아다니네요

**Comment by kimkang79** [comment]
넵 고생하셨습니다~! ^^
