### ISSUE TITLE
Grid tree view 에서 체크박스 에디터 기능 사용시 disabled 된 체크박스도 일괄적용되는 현상

### ISSUE THREAD

**Issue by groovedk** [ax5ui/ax5ui-grid#48]
그리드 트리뷰에서 부모 체크시 자식노드도 같이 체크되는 부분에서 
disable 된 체크박스도 적용이 되는 문제가 있네요. 

![image](https://cloud.githubusercontent.com/assets/5887628/25465469/658f77c4-2b3d-11e7-9892-d084f4e80931.png)

자식노드까지 체크가 잘 됩니다. 
하지만 디스에이블 된 아이들도 값이 변경 되네요.
![image](https://cloud.githubusercontent.com/assets/5887628/25465488/7d255476-2b3d-11e7-9133-7491929ee8f3.png)

부모를 체크해서 자식들을 체크할때 updateChildRows 호출시 _updatedata 에 함수를 받아서 피해갈 로직을 직접 작성하거나, 디스에이블 조건에 부합시 체크로직을 타지 않으면 되지 않을까 합니다.

감사합니다.

**Comment by thomasJang** [comment]
```js
this.self.updateChildRows(this.dindex, {isChecked: this.item.isChecked}, {filter: function (item) {
    return item.saleType != "A";
}});
```

3번째 인자로 option을 추가하고 option에 filter 함수를 사용할 수 있습니다.
filter함수에는 item, index가 this로 전달되고 있고, 첫번째 아규먼트로 item이 전달됩니다.

**Comment by groovedk** [comment]
잘됩니다!! 캄사합니다!
