### ISSUE TITLE
Contextmenu IE, Chrome 스타일

### ISSUE THREAD

**Issue by buukiki** [ax5ui/ax5ui-grid#51]
![cap 2017-04-28 13-41-41-657](https://cloud.githubusercontent.com/assets/19723674/25514529/9cbd6b8a-2c18-11e7-84bd-f806679f744a.jpg)
위에 크롬으로 볼땐 선명한데 IE11 로 볼때는 흐리게 나오네요
이게 한글로 메뉴를 만들어 보니깐 더 흐리게 됩니다.

**Comment by thomasJang** [comment]
CSS 애니메이션을 제거 해야 해결 될 것 같네요. IE 콘솔에서 CSS한번 체크해주시면 감사하겠습니다.

**Comment by thomasJang** [comment]
![image](https://cloud.githubusercontent.com/assets/5884902/25530450/41986f54-2c61-11e7-8f2c-ade79998a2f0.png)
제제 IE11에서는 또렷한데요.. 머가 원인일까요..

**Comment by aeei** [comment]
<img width="1341" alt="2017-04-28 11 12 07" src="https://cloud.githubusercontent.com/assets/18022843/25532399/37805caa-2c68-11e7-9124-2e230316ea1f.png">
저도 IE11에서 또렷하게 잘 나옵니다. '-'?

**Comment by buukiki** [comment]
![cap 2017-05-04 12-08-57-155](https://cloud.githubusercontent.com/assets/19723674/25689376/79c15f48-30c2-11e7-9e8d-c39053cdd2ae.png)
음...제PC만 문제인건가요? 왜 흐리지...
