### ISSUE TITLE
그리드 소팅에 문제가 있어 보입니다. 

### ISSUE THREAD

**Issue by groovedk** [ax5ui/ax5ui-grid#54]
일단 기본 스타일이 변경이 되었네요. 의도하신건지는 모르겠다만 화살표가 위아래가 붙어보입니다. 
![image](https://cloud.githubusercontent.com/assets/5887628/25804932/9b9cce12-3438-11e7-8bca-0dfd5b6ee15a.png)

그리고 소팅을 하고난뒤에 기본으로 돌아가면 처음에 소팅으로 돌아가지를 않습니다. 

desc
![image](https://cloud.githubusercontent.com/assets/5887628/25805021/008ac02c-3439-11e7-9655-543d625dd0e5.png)

asc
![image](https://cloud.githubusercontent.com/assets/5887628/25805042/19adf326-3439-11e7-8b39-38470530633a.png)

그리고 한번더

![image](https://cloud.githubusercontent.com/assets/5887628/25805218/e3f85108-3439-11e7-9c1c-d557973dc206.png)

원 데이터로 돌아가질 않네요;;;

**Comment by thomasJang** [comment]
문제가 해결 되셨는지 확인해주시고 close부탁합니다.

**Comment by groovedk** [comment]
수정된 내용 잘 보았습니다. 
허나 소팅을 풀었을때 원 데이터로 돌아가지는 않고 있습니다.  초기 데이터의 오리진 인덱스를 가지고 처리해보는건 어떨지 건의 드려 봅니다.

**Comment by thomasJang** [comment]
오리지널 인덱스를 적용해보았습니다. 부디 문제가 영원히 없기를 ~
