### ISSUE TITLE
onDataChanged 기능 관련 문의 드립니다.

### ISSUE THREAD

**Issue by kimkang79** [ax5ui/ax5ui-grid#55]
Grid상에서 컬럼의 값이 수정 된 경우에만 체크 될 수 있도록 하기위해 아래와 같이 구현하였습니다.
![111](https://cloud.githubusercontent.com/assets/12708061/26096863/90bdb288-3a5d-11e7-806c-62de2023491c.png)

위의 방법으로 체크된값에 대하여 체크박스를 직접 클릭(빨강색)하였을때 체크가 풀리는게 정상적인 상황이라고 추측이 되는데요, 체크가 풀리지 않고 있습니다.
![222](https://cloud.githubusercontent.com/assets/12708061/26096970/f4afb458-3a5d-11e7-8e41-7c8aa45f0abd.png)

그리드 설정은 아래와 같이 되어 있습니다.
![333](https://cloud.githubusercontent.com/assets/12708061/26097427/7a6202f8-3a5f-11e7-984e-29f3325bdcba.png)

기능 확인 부탁드립니다.

**Comment by thomasJang** [comment]
onDataChanged에서 console.log(this) 해보시면 사용할 수 있는 변수들이 있습니다. 변경된 값이 파악된다면 체크박스가 변경된 상황을 예외 처리 하면 될 것 같구요.

![image](https://cloud.githubusercontent.com/assets/5884902/26111375/e821b024-3a8f-11e7-9583-4263bfbcc060.png)

혹시 몰라 체크해보니 `key`를 알수 있네요.
```js
if(this.key !== "__selected__"){
 this.self.select.....
}
```

하시면 되지 않을까 싶습니다.

**Comment by kimkang79** [comment]
감사합니다!
알려주신 방법을 이용하여 아래처럼 구현하였습니다.

혹시 저처럼 헤매는 분 있다면 아래 내용 참고 해 주시기 바랍니다.
![111](https://cloud.githubusercontent.com/assets/12708061/26133725/45c9d7f2-3ae4-11e7-83b4-6009be866ebf.png)
