### ISSUE TITLE
그리드 속도가 느린듯한데..

### ISSUE THREAD

**Issue by david80** [ax5ui/ax5ui-grid#59]
그리드 방식이 div 형태로 되어있어 속도가 느린듯합니다..
개선방향은 가지고 있는지 궁금하네요~

데이터가 많을 경우 체크박스 클릭시 딜레이가 좀 많이 생기는거 같습니다.
테이블 코딩으로 했을 경우에는 이런 차이가 너무 느껴지는데요..

CSS 관련해서 액션이라든지 효과를 최대한 빼야 속도가 어느정도 개선이 될듯하구요..
div 셀 높이를 기본으로 작게 잡아야 속도가 빨라집니다.

**Comment by david80** [comment]
답변감사합니다.
아 제가 잘못본거 같군요 ~ table tr td 로 되어있네요. 안에 td안에 span으로 되어있는 구조였네요.

**Comment by SQLGate** [comment]
개발자분이 제목만 보면 무척 섭섭해 했을것 같아요.

**Comment by thomasJang** [comment]
IE 스크롤 성능 개선 작업이 진행 되었습니다. 전보다 나아졌는지 한번 봐주시고 이슈 닫아주세요
