### ISSUE TITLE
그리드에 컨텍스트 메뉴 연결시 문제가 있네요

### ISSUE THREAD

**Issue by groovedk** [ax5ui/ax5ui-grid#64]
그리드에 컨텍스트 메뉴를 달아 사용하려 하는데 
우클릭 후 컨텍스트의 내용을 클릭하면 문제가 없지만 각각 레코드들에서 컨텍스트메뉴를 우클릭으로 열기만 하고 선택을 안하다가 선택을 하면 클릭 이벤트가 중복으로 나옵니다. 

데모페이지를 예를들어 설명을 해보면
http://ax5.io/ax5ui-grid/demo/21-contextmenu.html

![image](https://cloud.githubusercontent.com/assets/5887628/26760262/a9a58dca-494e-11e7-93c3-75300286e502.png)

1번부터 5번까지 차례대로 컨텍스트 메뉴를 오픈만 하고 컨텍스트 안의 내용을 누르지 않은채로 
6번째 레코드에서 컨텍스트 메뉴로 나오는 아이템을 클릭을 하면 

![image](https://cloud.githubusercontent.com/assets/5887628/26760267/e1e578f8-494e-11e7-8f96-271a7e290c72.png)

한번 클릭시 클릭전까지 열었던 컨텍스트 메뉴의 클릭 이벤트가 한번에 발생됩니다.

같은 내용의 확장으로 컨텍스트를 데이터의 상태에 따라 다르게 띄우는 경우에는 클릭 위치에따라 다른 메뉴들이 선택 되는 문제도 있습니다. 

1번 레코드의 컨텍스트가 
 1. 추가
 2. 수정
 3. 삭제

2번 레코드의 컨택스트가 
 1. 추가
 2. 수정
 3. 이동
 4. 삭제

일경우 1번 컨텍스트를 열고 아무것도 선택하지 않은채 2번 컨텍스트메뉴를 열어 세번째 이동을 클릭했을때 1번 레코드의 삭제와, 2번레코드의 이동이 동시에 발생합니다.

**Comment by thomasJang** [comment]
버그찾아주셔서 대단히 감사합니다.
수정된 버전을 배포중입니다. 패치후 테스트 해주세요. ax5ui-menu를 패치해주세요.
