### ISSUE TITLE
그리드 초기화 문의 드립니다.

### ISSUE THREAD

**Issue by kimkang79** [ax5ui/ax5ui-grid#68]
언제나 감사드립니다.

그리드내의 데이터를 한번에 없애고 싶습니다(빈 그리드로 초기화).

그리드에서 체크박스를 사용하고 있기 때문에 
	.deleteRow("selected");
위의 기능을 사용하려 했지만, 체크되지 않은 데이터는 그대로 남는 단점이 있습니다.
해결방법이 있을까요?

**Comment by aeei** [comment]
정석은 아닌것 같습니다만.. 빈 배열로 데이터를 초기화하면 되지 않을까요??
```javascript
grid.setData([]);
```

**Comment by kimkang79** [comment]
Oh !!! 

grid.selectAll();  --->  grid.deleteRow("selected");
이런식으로 처리하려 했는데...
aeei님이 제시해 주신 방법이 훨씬 깔끔하네요.

좋은 아이디어 감사드립니다 ^^
