### ISSUE TITLE
컬럼에 hidden 속성이 없는 건가요?

### ISSUE THREAD

**Issue by jaeyeolkim** [ax5ui/ax5ui-grid#71]
안녕하세요. ax5ui-grid 도입을 검토중에 있습니다.
키가 되는 컬럼값을 hidden 속성으로 정의하여 숨겨두고 싶은데요.
속성이 없는건지 제가 못 찾는 건지요^^;

**Comment by thomasJang** [comment]
아래 이슈 체크 해보시구요.
https://github.com/ax5ui/ax5ui-grid/issues/7

그리고 키가되는 컬럼값은 columns에서 선언 안하시면 됩니다. 데이터에 키가 있다고 그리드에 출력되지 않습니다.

**Comment by jaeyeolkim** [comment]
우와~ 빠른 답변 감사드립니다.
jgGrid 같은 경우는 컬럼으로 선언해주어야만 했는데
이건 그렇지 않아서 좋군요^^

**Comment by groovedk** [comment]
Ax5 가 더 좋ㅅ.....
