### ISSUE TITLE
excel export 버그 문의 입니다.

### ISSUE THREAD

**Issue by mucsiza** [ax5ui/ax5ui-grid#73]
그리드 구 버젼인 1.3.32 에서는 excel export 시에 한글이 문제없이 나왔습니다.

하지만 현재 마스터 버젼인 1.4.78 에서는 excel export 시에 한글이 안나옵니다.
모든 한글 컬럼에 text&nbsp; 라고만 문자만 찍혀 있습니다.

확인 부탁 드립니다.

**Comment by thomasJang** [comment]
버그 수정되었습니다.
버그를 찾아주셔서 대단히 감사합니다.
