### ISSUE TITLE
데이타 없을때 문구 처리를 할수 있는 방법이 있을까요 ?

### ISSUE THREAD

**Issue by ytechinfo** [ax5ui/ax5ui-grid#81]
데이타 없을때 문구 처리를 할수 있는 방법이 있을까요 ?

**Comment by thomasJang** [comment]
질문을 조금만 더 명확하게 해주세요.

**Comment by ytechinfo** [comment]
firstGrid.setData(# []);

setData시 데이타 없을경우에 . 

그리드안에 "조회결과가 없습니다. " 이런 문구를 넣을수 있는방법이나 있는지를 질문한것입니다.

**Comment by ytechinfo** [comment]
https://github.com/ytechinfo/ax5ui-grid 이쪽에 fork해서는수정해서 넣어 놨습니다. 
이렇게 해서 수정해서 써도 될른지요 ?

**Comment by thomasJang** [comment]
포크해서 사용하셔도 무방합니다.
