### ISSUE TITLE
deleteRow 에서 index값을 넣을경우 . error가 발생합니다. 

### ISSUE THREAD

**Issue by ytechinfo** [ax5ui/ax5ui-grid#85]
deleteRow 에서 index값을 넣을경우
아래와 같은 에러가 발생합니다. 
ax5grid.js:4909 Uncaught invalid argument _dindex

찾아보니. 
숫자 가 들어가면 true고  문자가 들어가면  false를 넘겨 주고 있습니다. 
ax5.util.isNumber(1)
true
ax5.util.isNumber('1')
false

**Comment by thomasJang** [comment]
deleteRow(Number('1')) 이런식으로 해주셔야 겠습니다. 아규먼트가 숫자 또는 예약어가 아니면 처리 안하도록 되어 있습니다.

**Comment by ytechinfo** [comment]
네 감사합니다.
