### ISSUE TITLE
inline editor 모드에서 editor type = select의 경우

### ISSUE THREAD

**Issue by rcn408** [ax5ui/ax5ui-grid#9]
Grid의 inline editor모드일경우
editor type = select 의 컬럼을 수정하게 되면
선택한 selectbox의 optionValue 값이 해당 컬럼의 값으로 변경됩니다.

이경우 코드는 따로 어딘가에 두고  optionText 값이 column에 들어가야 할텐데..
어찌 할바를 모르겠네요..
그냥 optionValue 로만 들어가니...
선택한 코드와 코드값을 모두 그리드 Row에 표현하고 싶은데..힘드네요

무슨 방법이 없을까요?

**Comment by thomasJang** [comment]
select 의 코드를 별도의 오브젝트로 만들어두고 연결해서 쓰시는 어렵지 않을 실 겁니다. 
그게 속도도 더 빠르구요

**Comment by rcn408** [comment]
{key: 'inoutSxnNm', label: '<b>구분</b>', width: 80, align: 'center', editor: {type: 'select', config: {columnKeys: {optionValue: 'code', optionText: 'codeNm'}, options: **inoutSxnList**}}}

요러케 object (inoutSxnList) 로 코드 리스트를 만들어서 쓰고 있습니다.

![image](https://cloud.githubusercontent.com/assets/24471341/21298389/dfb08a4a-c5d3-11e6-8138-cde72ff2e619.png)

이렇게 자사와 외주 코드가 있으면......

![image](https://cloud.githubusercontent.com/assets/24471341/21298397/028b034c-c5d4-11e6-8098-acf81488bd96.png)

select box가 될때...코드만 나오게 되네요....

code와 codenm 이 있을경우..
원래 Row에는 codenm으로 보일테고...
select로 선택할때도 codenm으로 보이지만
실제 값은 code로 관리되어야 합니다.

도통 감이 안오네요..^^;

**Comment by thomasJang** [comment]
@aeei

**Comment by aeei** [comment]
[formatter](http://ax5.io/ax5ui-grid/demo/1-formatter.html) 를 사용하시면 문제를 해결하실 수 있습니다.

<img src="https://github.com/aeei/note/blob/master/images/inout.png?raw=true">

```javascript
{
    key: 'inoutSxnNm',
    label: '구분',
    width: 80,
    align: 'center',
    formatter: function () {
        // 원하시는 반복문을 사용하세요.
        for (var i = 0; i < inoutSxnList.length; i++) {
            if (inoutSxnList[i].code == this.value) {
                return inoutSxnList[i].codeNm;
            }
        }
    },
    editor: {
        type: 'select',
        config: {columnKeys: {optionValue: 'code', optionText: 'codeNm'}, options: inoutSxnList}
    }
}
```
---

아래와 같이 맵 객체를 사용하시면 formatter 안에 코드를 좀 더 간결하게 하실 수 있습니다.
```javascript
var inoutSxnMap = {};
inoutSxnList.forEach(function (n) {
    inoutSxnMap[n.code] = n.codeNm;
}),
```
```javascript
{
    key: 'inoutSxnNm',
    label: '구분',
    width: 80,
    align: 'center',
    formatter: function () {
        return inoutSxnMap[this.value];
    },
    editor: {
        type: 'select',
        config: {columnKeys: {optionValue: 'code', optionText: 'codeNm'}, options: inoutSxnList}
    }
}
```

---
콘솔의 결과를 보시면 실제 값도 code값이 출력되는 것을 확인하실 수 있습니다.
<img src="https://github.com/aeei/note/blob/master/images/console.png?raw=true">

**Comment by thomasJang** [comment]
👍

**Comment by rcn408** [comment]
오호라..이런 방법이..^^ 감사합니다.
